In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1,sort=True)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1,ser2],keys=['cat','cat2'])

cat   T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
from numpy.random import randn 

In [13]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [14]:
dframe1

X         Y         Z
0  0.565969 -1.132845  2.409789
1 -0.423907 -0.406902  1.405899
2 -0.299841  0.371207 -0.471533
3 -0.222890 -0.929882  0.322997

In [15]:
dframe2

Y         Q         X
0 -0.425560  1.352321  0.259108
1  1.003174 -1.274586  0.592797
2  1.248062  0.749422  0.408034

In [17]:
pd.concat([dframe1,dframe2],sort=True)

Q         X         Y         Z
0       NaN  0.565969 -1.132845  2.409789
1       NaN -0.423907 -0.406902  1.405899
2       NaN -0.299841  0.371207 -0.471533
3       NaN -0.222890 -0.929882  0.322997
0  1.352321  0.259108 -0.425560       NaN
1 -1.274586  0.592797  1.003174       NaN
2  0.749422  0.408034  1.248062       NaN

In [18]:
pd.concat([dframe1,dframe2],ignore_index=True,sort=True)

Q         X         Y         Z
0       NaN  0.565969 -1.132845  2.409789
1       NaN -0.423907 -0.406902  1.405899
2       NaN -0.299841  0.371207 -0.471533
3       NaN -0.222890 -0.929882  0.322997
4  1.352321  0.259108 -0.425560       NaN
5 -1.274586  0.592797  1.003174       NaN
6  0.749422  0.408034  1.248062       NaN